[package]
name = "authz"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
jsonwebtoken = "9.3"
chrono = { workspace = true }
anyhow = { workspace = true }
futures-util = "0.3"
